export const READ_BASKET = "READ_BASKET";
export const REMOVE_BASKET = "REMOVE_BASKET";
export const SEND_PRODUCTS = "SEND_PRODUCTS";
export const ADD_BASKET = "ADD_BASKET";
export const EDIT_BASKET = "EDIT_BASKET";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_ADMIN_PRODUCTS = "SET_ADMIN_PRODUCTS";
export const SET_ADMIN_PRODUCTS_CATIGORY = "SET_ADMIN_PRODUCTS_CATIGORY";
